name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      RELEASEVER: "0.0.24"
      SPHINXDFT_DATA_VER: "0.0.1"
      SPHINXDFT_DATA_BUILD: "0"
      GPAW_DATA_VER: "0.9.20000"
      GPAW_DATA_BUILD: "0"
      IPRPY_DATA_VER: "2023.07.25"
      IPRPY_DATA_HASH: "pyhd8ed1ab"
      IPRPY_DATA_BUILD: "0"

    steps:
    - uses: actions/checkout@v2
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: conda-package-handling
        version: 1.0
    - name: Build Package
      run: |
        mkdir build
        cd build
        wget https://anaconda.org/conda-forge/sphinxdft-data/${SPHINXDFT_DATA_VER}/download/noarch/sphinxdft-data-${SPHINXDFT_DATA_VER}-${SPHINXDFT_DATA_BUILD}.tar.bz2 -O sphinxdft-data.tar.bz2
        wget https://anaconda.org/conda-forge/gpaw-data/${GPAW_DATA_VER}/download/linux-64/gpaw-data-${GPAW_DATA_VER}-${GPAW_DATA_BUILD}.tar.bz2 -O gpaw-data.tar.bz2
        wget https://anaconda.org/conda-forge/iprpy-data/${IPRPY_DATA_VER}/download/noarch/iprpy-data-${IPRPY_DATA_VER}-${IPRPY_DATA_HASH}_${IPRPY_DATA_BUILD}.conda -O iprpy-data.conda
        mkdir sphinxdft-data gpaw-data iprpy-data resources
        tar -xjvf sphinxdft-data.tar.bz2 -C sphinxdft-data
        tar -xjvf gpaw-data.tar.bz2 -C gpaw-data
        cph extract iprpy-data.conda
        mv ../atomicrex resources
        mv ../atomistics resources
        mv ../interactive resources
        mv ../lammps resources
        mv ../mlip resources
        mv ../runner resources
        mv ../pacemaker resources
        mv ../sphinx resources
        mv ../thermodynamics resources
        mv ../LICENSE resources
        mv ../damask resources
        mv ../templates resources
        mv ../dynamic resources
        mkdir resources/lammps/potentials
        mv iprpy-data/share/iprpy/potentials_lammps.csv resources/lammps/potentials/potentials_lammps.csv
        mv iprpy-data/share/iprpy/potential_LAMMPS resources/lammps/potentials/potential_LAMMPS
        find resources/lammps/potentials -name "*.json" -exec rm -rf {} \;
        find resources/lammps/potentials -name "*.rst" -exec rm -rf {} \;
        find resources/lammps/potentials -name "*.ipynb" -exec rm -rf {} \;
        mkdir -p resources/gpaw
        mv gpaw-data/share/gpaw resources/gpaw/potentials
        mv sphinxdft-data/share/sphinxdft/jth-gga-pbe resources/sphinx/potentials
        tar -zcvf resources-${RELEASEVER}.tar.gz resources
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASEVER }}
        release_name: Release ${{ env.RELEASEVER }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/resources-${{ env.RELEASEVER }}.tar.gz
        asset_name: resources.tar.gz
        asset_content_type: application/zip
